-- -SBW- v1.6.55.1+
-- Hotfixes SQL aplicados manualmente no Supabase durante validação real.
--
-- Correções feitas:
-- 1. Criada/corrigida RPC public.sbw_create_tournament_organizer(p_payload jsonb).
-- 2. Ajustado tournament_organizers.games para salvar como text[].
-- 3. Ajustada constraint tournament_organizers_status_check para aceitar status active.
-- 4. Corrigida RPC public.sbw_get_my_tournament_organizer_access(), removendo uso de display_name inexistente.
-- 5. Criada função auxiliar public.sbw_slugify(text).
-- 6. Corrigida RPC public.sbw_create_tournament_for_organizer(p_payload jsonb), usando organizer_id como uuid.
--
-- Resultado validado:
-- Organização real criada no Supabase.
-- Criador vira owner/admin da organização.
-- Botão Criar Torneio aparece para usuário com permissão.
-- Torneio criado normalmente e vinculado à organização real.